name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install uv
          uv venv && uv pip install -e .

      # - name: Lint and format
      #   run: |
      #     uv add flake8 black
      #     black .

      - name: Run tests
        run: |
          pytest || echo "No tests found"

      - name: Build Docker image
        run: |
          docker build -t breeze:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag breeze:latest ${{ secrets.DOCKERHUB_USERNAME }}/breeze:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/breeze:latest
